Ajusta mensagem do carregamento de novidades
analytics-ufcg/ta-na-mesa pull request #220
Opened 2020-12-03 17:29 UTC by biabs1

2020-12-03 20:18 UTC, gileadekelvin requested changes
Dúvida sobre o spinner

2020-12-03 20:18 UTC, gileadekelvin commented on client/src/app/municipio/novidades/novidades.component.html
> +<div [hidden]="novidades?.length || (loading$ | async) === true">
o spinner que está sendo exibido na interface é esse ou da linha 2?

2020-12-03 22:16 UTC, biabs1 commented on client/src/app/municipio/novidades/novidades.component.html
> +<div [hidden]="novidades?.length || (loading$ | async) === true">
Acho que era o da linha 2. Removi este.

2020-12-07 23:12 UTC, gileadekelvin approved these changes

2020-12-07 23:12 UTC, merged